### ISSUE TITLE
Auto-complete

### ISSUE THREAD

**Issue by eveliotc** [hovsater/github.alfredextension#3]
Hi,

Thanks for this awesome extension, just a feature request here, I'm lazy and love the tab key, I would love to have auto completion, user could authorize extension to read repos and users and set them as source for auto-completion, not sure if it is technically possible.

Thanks a lot!

**Comment by hovsater** [comment]
Hi, @eveliotc.

At the moment this isn't technical possible due to limitations in Alfred and the lack of a developer API. Andrew, the developer of Alfred, released an sneak peek of Alfred V2 yesterday, which seem to address many of these issues.

I got a lot of new features coming in the next major release. Meanwhile, please be patient.

If absolutely necessary, I could implement an alias-feature. That would allow one to create aliases that point to actual commands.

For instance: `github alias me KevinSjoberg` would allow you to then run `github :me` and that would expand to `github KevinSjoberg`.
